
package xyz.oeste.integracion.endpoints;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegionEndPoint", targetNamespace = "http://endpoints.integracion.oeste.xyz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegionEndPoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns xyz.oeste.integracion.endpoints.Region
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "servicio", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.Servicio")
    @ResponseWrapper(localName = "servicioResponse", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.ServicioResponse")
    @Action(input = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/servicioRequest", output = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/servicioResponse")
    public Region servicio(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "servicioEliminar", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.ServicioEliminar")
    @ResponseWrapper(localName = "servicioEliminarResponse", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.ServicioEliminarResponse")
    @Action(input = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/servicioEliminarRequest", output = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/servicioEliminarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/servicioEliminar/Fault/Exception")
    })
    public void servicioEliminar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertar", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.Insertar")
    @ResponseWrapper(localName = "insertarResponse", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.InsertarResponse")
    @Action(input = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/insertarRequest", output = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/insertarResponse")
    public void insertar(
        @WebParam(name = "arg0", targetNamespace = "")
        Region arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizar", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.Actualizar")
    @ResponseWrapper(localName = "actualizarResponse", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.ActualizarResponse")
    @Action(input = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/actualizarRequest", output = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/actualizarResponse")
    public void actualizar(
        @WebParam(name = "arg0", targetNamespace = "")
        Region arg0);

    /**
     * 
     * @return
     *     returns java.util.List<xyz.oeste.integracion.endpoints.Region>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarTodos", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.BuscarTodos")
    @ResponseWrapper(localName = "buscarTodosResponse", targetNamespace = "http://endpoints.integracion.oeste.xyz/", className = "xyz.oeste.integracion.endpoints.BuscarTodosResponse")
    @Action(input = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/buscarTodosRequest", output = "http://endpoints.integracion.oeste.xyz/RegionEndPoint/buscarTodosResponse")
    public List<Region> buscarTodos();

}
