package xyz.oeste.integracion.model;
// Generated 18/08/2018 11:03:45 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pokemon generated by hbm2java
 */
@Entity
@Table(name = "pokemon", schema = "public")
public class Pokemon implements java.io.Serializable {

	private int idPokemon;
	private Region region;
	private String nombre;
	private Set<Poke> pokes = new HashSet<Poke>(0);
	private Set<PokeTipo> pokeTipos = new HashSet<PokeTipo>(0);

	public Pokemon() {
	}

	public Pokemon(int idPokemon) {
		this.idPokemon = idPokemon;
	}

	public Pokemon(int idPokemon, Region region, String nombre, Set<Poke> pokes, Set<PokeTipo> pokeTipos) {
		this.idPokemon = idPokemon;
		this.region = region;
		this.nombre = nombre;
		this.pokes = pokes;
		this.pokeTipos = pokeTipos;
	}

	@Id

	@Column(name = "id_pokemon", unique = true, nullable = false)
	public int getIdPokemon() {
		return this.idPokemon;
	}

	public void setIdPokemon(int idPokemon) {
		this.idPokemon = idPokemon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_region")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pokemon")
	public Set<Poke> getPokes() {
		return this.pokes;
	}

	public void setPokes(Set<Poke> pokes) {
		this.pokes = pokes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pokemon")
	public Set<PokeTipo> getPokeTipos() {
		return this.pokeTipos;
	}

	public void setPokeTipos(Set<PokeTipo> pokeTipos) {
		this.pokeTipos = pokeTipos;
	}

}
