package xyz.oeste.integracion.model;
// Generated 18/08/2018 11:03:45 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PokeTipo generated by hbm2java
 */
@Entity
@Table(name = "poke_tipo", schema = "public")
public class PokeTipo implements java.io.Serializable {

	private PokeTipoId id;
	private Pokemon pokemon;
	private Tipo tipo;

	public PokeTipo() {
	}

	public PokeTipo(PokeTipoId id, Pokemon pokemon, Tipo tipo) {
		this.id = id;
		this.pokemon = pokemon;
		this.tipo = tipo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPokemon", column = @Column(name = "id_pokemon", nullable = false)),
			@AttributeOverride(name = "idTipo", column = @Column(name = "id_tipo", nullable = false)) })
	public PokeTipoId getId() {
		return this.id;
	}

	public void setId(PokeTipoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pokemon", nullable = false, insertable = false, updatable = false)
	public Pokemon getPokemon() {
		return this.pokemon;
	}

	public void setPokemon(Pokemon pokemon) {
		this.pokemon = pokemon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pokemon", nullable = false, insertable = false, updatable = false)
	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

}
