package xyz.oeste.integracion.model;
// Generated 18/08/2018 11:03:45 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Poke generated by hbm2java
 */
@Entity
@Table(name = "poke", schema = "public")
public class Poke implements java.io.Serializable {

	private Integer idPoke;
	private Pokemon pokemon;
	private String nombre;
	private Integer idEntrenador;

	public Poke() {
	}

	public Poke(Integer idPoke) {
		this.idPoke = idPoke;
	}

	public Poke(Integer idPoke, Pokemon pokemon, String nombre, Integer idEntrenador) {
		this.idPoke = idPoke;
		this.pokemon = pokemon;
		this.nombre = nombre;
		this.idEntrenador = idEntrenador;
	}

	@Id

	@Column(name = "id_poke", unique = true, nullable = false)
	public Integer getIdPoke() {
		return this.idPoke;
	}

	public void setIdPoke(Integer idPoke) {
		this.idPoke = idPoke;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pokemon")
	public Pokemon getPokemon() {
		return this.pokemon;
	}

	public void setPokemon(Pokemon pokemon) {
		this.pokemon = pokemon;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "id_entrenador")
	public Integer getIdEntrenador() {
		return this.idEntrenador;
	}

	public void setIdEntrenador(Integer idEntrenador) {
		this.idEntrenador = idEntrenador;
	}

}
