package xyz.oeste.integracion.model;
// Generated 18/08/2018 11:03:45 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name = "tipo", schema = "public")
public class Tipo implements java.io.Serializable {

	private int idTipo;
	private String tipo;
	private Set<PokeTipo> pokeTipos = new HashSet<PokeTipo>(0);

	public Tipo() {
	}

	public Tipo(int idTipo) {
		this.idTipo = idTipo;
	}

	public Tipo(int idTipo, String tipo, Set<PokeTipo> pokeTipos) {
		this.idTipo = idTipo;
		this.tipo = tipo;
		this.pokeTipos = pokeTipos;
	}

	@Id

	@Column(name = "id_tipo", unique = true, nullable = false)
	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pokemon")
	public Set<PokeTipo> getPokeTipos() {
		return this.pokeTipos;
	}

	public void setPokeTipos(Set<PokeTipo> pokeTipos) {
		this.pokeTipos = pokeTipos;
	}

}
